### ISSUE TITLE
Can't load train_set

### ISSUE THREAD

**Issue by Wiikk** [ElementAI/embedding-propagation#5]
Hi, thanks for your excellent work.
I use the pickled version of mini-imagenet dataset and set the dataset name "episodic_miniimagenet_pkl".
However, when I run the pre-training code, I get the following error message:

Traceback (most recent call last):
  File "trainval.py", line 220, in <module>
    pretrained_weights_dir=args.pretrained_weights_dir)
  File "trainval.py", line 143, in trainval
    score_dict.update(model.train_on_loader(train_loader))
  File "/remote-home/my/Code/embedding-propagation-master/src/models/pretraining.py", line 172, in train_on_loader
    for batch_idx, batch in enumerate(data_loader):     
  File "/usr/local/miniconda3/envs/dl10/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 346, in __next__
    data = self.dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/usr/local/miniconda3/envs/dl10/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/usr/local/miniconda3/envs/dl10/lib/python3.6/site-packages/torch/utils/data/_utils/collate.py", line 75, in default_collate
    return {key: default_collate([d[key] for d in batch]) for key in elem}
  File "/usr/local/miniconda3/envs/dl10/lib/python3.6/site-packages/torch/utils/data/_utils/collate.py", line 75, in <dictcomp>
    return {key: default_collate([d[key] for d in batch]) for key in elem}
  File "/usr/local/miniconda3/envs/dl10/lib/python3.6/site-packages/torch/utils/data/_utils/collate.py", line 82, in default_collate
    raise TypeError(default_collate_err_msg_format.format(elem_type))
TypeError: default_collate: batch must contain tensors, numpy arrays, numbers, dicts or lists; found <class 'NoneType'>

Could you give some advice on dealing with NoneType values? Thanks a lot.

**Comment by MichalisLazarou** [comment]
Hey I have exactly the same problem how did you manage to solve it?

**Comment by Wiikk** [comment]
@MichalisLazarou
You can write a new class called "RotatedNonEpisodicMiniImagenetPkl" imitating "RotatedNonEpisodicMiniImagenet" in src/datasets/miniimagenet.py. This works for me.

**Comment by prlz77** [comment]
Thanks @Wiikk! Would you mind doing a pull request to include it in the repo?

**Comment by Wiikk** [comment]
@prlz77  Sure, I will do this later.

**Comment by prlz77** [comment]
Thank you :)
